### ISSUE TITLE
Erro ao clicar na opção 'Perfil' do 'Menu do Usuário'

### ISSUE THREAD

**Issue by cpereiraweb** [felipeArnold/filament-multi-tenancy-start-kit#1]
## Descrição do Problema
Ao clicar na opção 'Perfil' do 'Menu do Usuário' sou direcionado para o caminho '/admin/profile' e recebo o erro "Attempt to read property "name" on null"

## Como Reproduzir
1. Acessar o Painel (/admin)
2. Clicar no avatar do usuário para acessar o menu e, então, clicar na opção 'Perfil'

## Comportamento Esperado
Ser exibida a página de Perfil da Empresa, no caminho '/admin/wsoft/profile'

## Comportamento Atual
Aparentemente o sistema não consegue recuperar a propriedade 'name' do tenant atual e, com isso, não monta o caminho corretamente (/admin/profile).
Ao se inserir o nome do tenant manualmente na url, a página é exibida corretamente.

## Screenshots
![image](https://github.com/user-attachments/assets/0eca2799-5ade-4760-b0f7-9e5ecb166391)

Ao se inserir manualmente o nome do tenant na url, a página é exibida corretamente:
![image](https://github.com/user-attachments/assets/a2c34fb5-2a10-43e5-95a1-7e2bc90c34e9)

## Informações Adicionais
- Versão: commit #3528b6ea9424eeda2dc35395e17db15da1b74de5
- Sistema Operacional: Windows 11
- Navegador: Microsoft Edge Versão 131.0.2903.112 (Compilação oficial) (64 bits)

## Logs de Erro

**Comment by jefpes** [comment]
![{53AE48E9-B369-40F6-94D2-389E5A1C4AA8}](https://github.com/user-attachments/assets/d421dea8-8625-4367-8850-970a08b058d7)


resolucão

**Comment by felipeArnold** [comment]
Boa noite, foi criado um PR e corrigido o problema.
